pr:
  branches:
    include:
      - master
      - features/*
  paths:
    include:
      - day2/apps/dotnetcore/*

variables:
  configuration: release

stages:
  - stage: Build
    displayName: Build

    jobs:
      - job: Scm-API
        displayName: Build dotnetcore SCM-Api
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: ../dotnetcore/build/scm-api.yaml
            parameters:
              buildConfiguration: "$(configuration)"
