trigger: none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - day2/apps/frontend/*

variables:
  configuration: release

stages:
  - stage: Build
    displayName: Build

    jobs:
      - job: Build
        displayName: Build Frontend Components
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: jobs/build-scm-fe.yaml
